function(setup_day_flags)
  if (NOT EXISTS DAY_FLAGS)
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wall>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wextra>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Werror>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wextra-semi>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wpedantic>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wcast-qual>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wfloat-equal>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wunreachable-code>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wnon-virtual-dtor>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wshadow>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wold-style-cast>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wunused>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Woverloaded-virtual>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wconversion>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wsign-conversion>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wnull-dereference>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wdouble-promotion>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wformat=2>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wduplicated-cond>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wlogical-op>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wuseless-cast>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-Wno-psabi>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-fmodules>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-fno-strict-aliasing>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-march=native>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-fuse-linker-plugin>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-pipe>")
    list(APPEND DAY_FLAGS_LIST "$<$<COMPILE_LANGUAGE:CXX>:-fvisibility=hidden>")

    set(DAY_FLAGS ${DAY_FLAGS_LIST} CACHE INTERNAL "Warning flags for beef" FORCE)
  endif()
endfunction()

function(setup_day_build day_name)
  configure_file("${day_name}.txt" "${day_name}.txt" COPYONLY)
  add_executable(${day_name} "main.cpp")
  target_include_directories(${day_name} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/.)
  set_target_properties(${day_name} PROPERTIES CXX_MODULE_STD 1)
  set_target_properties(${day_name} PROPERTIES LINKER_LANGUAGE CXX)
  set_target_properties(${day_name} PROPERTIES INTERPROCEDURAL_OPTIMIZATION ON)
  target_compile_options(${day_name} PRIVATE ${DAY_FLAGS})
  target_link_libraries(${day_name} adventofcode_utility_library fmt::fmt scn::scn_module)
endfunction()
